import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaEnvelopeCircleCheck } from "react-icons/fa6";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <p className="border-2 z-50 border-dashed m-4 relative animate-logo origin-top-left shadow-2xl   from-gray-500 via-[#b4b2b2] to-gray-400 text-4xl border-gray-600 text-gray-800 italic font-bold flex-row flex ml-4 rounded-2xl w-fit p-1.5  bg-[#a4a3a3] " style={{fontFamily:"cursive",}}>my quick cv
      <FaEnvelopeCircleCheck className="ml-2 pt-3"></FaEnvelopeCircleCheck></p>
      <h1 className="bg-[#b4b2b2] z-10 relative  max-md:w-[400px] border-2 border-dotted font-semibold italic text-gray-700 border-gray-700 p-3 space-x-3 flex justify-center items-start rounded-2xl m-2">
        
        </h1>
        
        {children}
        <footer className="bg-gray-800  p-3 flex justify-center items-center mt-20">
          <h1 className="mx-3">All rights reserved </h1>
          <h1>© {new Date().getFullYear() == 2025? 2025:`2025-${new Date().getFullYear()}`}</h1>
        <h1 className="mx-3">sleepy panda.</h1>
        </footer>
      </body>
    </html>
  );
}
