import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { FaEnvelopeCircleCheck } from "react-icons/fa6";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex-row  max-md:w-full bg-[#b4b2b2] p-5  mb-10 border-b-4 border-gray-400 border rounded-b-xl">
    <p className="border-2 border-dotted animate-logo origin-top-left shadow-2xl text-4xl border-gray-600 text-gray-800 italic font-bold flex-row flex ml-4 rounded-2xl w-fit p-1.5  bg-[#a4a3a3] " style={{fontFamily:"cursive",}}>my quick cv
      <FaEnvelopeCircleCheck className="ml-2 pt-3"></FaEnvelopeCircleCheck></p>
        </header>
        {children}
        <footer className="bg-gray-800  p-3 flex justify-center items-center mt-20">
          <h1 className="mx-3">All rights reserved </h1>
          <h1>© {new Date().getFullYear() == 2025? 2025:`2025-${new Date().getFullYear()}`}</h1>
        <h1 className="mx-3">sleepy panda.</h1>
        </footer>
      </body>
    </html>
  );
}
